-- Exams
ALTER TABLE exams ADD COLUMN IF NOT EXISTS time_limit_minutes INTEGER DEFAULT 60;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS passing_score INTEGER DEFAULT 60;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- Exam Questions
ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS points NUMERIC DEFAULT 1;
ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS order_index INTEGER DEFAULT 0;
ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS image_url TEXT;

-- Exam Options
ALTER TABLE exam_options ADD COLUMN IF NOT EXISTS match_text TEXT;
ALTER TABLE exam_options ADD COLUMN IF NOT EXISTS order_index INTEGER DEFAULT 0;

-- Exam Assignments
ALTER TABLE exam_assignments ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;

-- Exam Attempts
ALTER TABLE exam_attempts ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'IN_PROGRESS';
ALTER TABLE exam_attempts ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE exam_attempts ADD COLUMN IF NOT EXISTS score NUMERIC;

-- Exam Answers
ALTER TABLE exam_answers ADD COLUMN IF NOT EXISTS is_correct BOOLEAN DEFAULT FALSE;
ALTER TABLE exam_answers ADD COLUMN IF NOT EXISTS points_earned NUMERIC DEFAULT 0;
